### ISSUE TITLE
Arrow function but Composer allows PHP 7.3

### ISSUE THREAD

**Issue by ash-jc-allen** [rezaamini-ir/migrator#19]
Hey! When I was just making a PR, I noticed that in `src/Service/StructureParser.php` on line 32, the line is:

```php
return array_filter($this->structure, fn($value) => !is_null($value['type']));
```

This line uses an arrow function and (as far as I'm aware) these can only be used on PHP 7.4 upwards. However, the `composer.json` file looks like it allows PHP 7.3.

I'm guessing the `composer.json` just needs changing to make PHP 7.4 the minimum? Or just switching the arrow function back to a closure if you want to keep support for 7.3? I'm happy to make a PR for either if needed :)

**Comment by reziamini** [comment]
Thank, it was fixed!
