### ISSUE TITLE
Can not publish config file

### ISSUE THREAD

**Issue by stoneC0der** [rezaamini-ir/migrator#29]
OS: Xubuntu 20.04
Laravel 8
package version: 1.5

I successfully installed the package but when publishing the I get the following error:

No publishable resources for tag [migrator-config].

**Comment by abbasudo** [comment]
@stoneC0der try running `php artisan vendor:publish` and sroll tell you find migrators config and then type the number of the config and hit enter . for example in this screenshot its 29
![2021-12-21 14 40 (2)](https://user-images.githubusercontent.com/86796762/149633035-85993e6b-6836-4176-b5cd-3fb1a3cc9966.jpeg)

**Comment by reziamini** [comment]
Also, If there was no Tag for [migrator-config], execute this command:
```
php artisan package:discover --ansi
```

**Comment by stoneC0der** [comment]
@llabbasmkhll I did try that already and I do not see the migrator-config tag

Here all the tags available
![git-issue](https://user-images.githubusercontent.com/11365636/149681549-9e170feb-df11-4b1a-8ca0-c33588f5a92d.png)

@rezaamini-ir I also try that still not showing

I even remove the package, reinstalled it still not working I try with a diff project later

**Comment by reziamini** [comment]
Try this:
```shell
php artisan vendor:publish --provider="\Migrator\MigratorServiceProvider"
```

**Comment by stoneC0der** [comment]
After running composer dumpautoload multiple time it finally show the migrator-config
