### ISSUE TITLE
ignore (foreign key constraint) Features

### ISSUE THREAD

**Issue by iransoftnet1** [rezaamini-ir/migrator#34]
hi
There is a fundamental problem deleting the tables
We at phpmyadmin have the ability to ignore (foreign key constraint)
![44555](https://user-images.githubusercontent.com/45430743/153951061-a8a576e3-3d6d-499c-94fd-1f575ae8224e.png)

**Comment by reziamini** [comment]
It’s phpmyadmin feature not Migrator or Laravel.
