### ISSUE TITLE
fis this issue

### ISSUE THREAD

**Issue by Hancie123** [rezaamini-ir/migrator#44]
Problem 1
    - rezaamini-ir/migrator[1.0.0, ..., 1.5.3] require illuminate/support ^6.0|^7.0|^8.0 -> found illuminate/support[v6.0.0, ..., v6.20.44, v7.0.0, ..., v7.30.6, v8.0.0, ..., v8.83.27] but these were not loaded, likely because it conflicts with another require.
    - rezaamini-ir/migrator[1.5.4, ..., 1.5.5] require illuminate/support ^6.0|^7.0|^8.0|^9.0 -> found illuminate/support[v6.0.0, ..., v6.20.44, v7.0.0, ..., v7.30.6, v8.0.0, ..., v8.83.27, v9.0.0, ..., v9.52.16] but these were not loaded, likely because it conflicts with another require.
    - rezaamini-ir/migrator[1.5.6, ..., 1.5.8] require livewire/livewire ^1.0|^2.5 -> found livewire/livewire[v1.0.0, ..., v1.3.9, v2.5.0, ..., v2.12.6] but it conflicts with your root composer.json require (^3.0).
    - Root composer.json requires rezaamini-ir/migrator * -> satisfiable by rezaamini-ir/migrator[1.0.0, ..., 1.5.8].

Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.
You can also try re-running composer require with an explicit version constraint, e.g. "composer require rezaamini-ir/migrator:*" to figure out if any version is installable, or "composer require rezaamini-ir/migrator:^2.1" if you know which you need.

**Comment by nowodev** [comment]
Hi. Did you find a solution to this?

**Comment by reziamini** [comment]
@nowodev @Hancie123 Would you please try with 1.5.9 tag?

**Comment by nowodev** [comment]
@reziamini 
<img width="1368" alt="Screenshot 2024-05-03 at 6 19 43 AM" src="https://github.com/reziamini/migrator/assets/43044740/d89a46af-d8dd-4344-8acf-a1ad9e7f8794">
I got this error

**Comment by reziamini** [comment]
Fixed in 1.6.0
