### ISSUE TITLE
Access level to Migrator\Http\Livewire\Migration\Create::getRules() must be public (as in class Livewire\Component)

### ISSUE THREAD

**Issue by walidalyosef** [rezaamini-ir/migrator#48]
Symfony \ Component\ ErrorHandler \ Error \ FatalError 
PHP 8.3.6
11.8.0
Access level to Migrator\Http\Livewire\Migration\Create::getRules() must be public (as in class Livewire\Component)

```
protected function getRules()

    {

        return [

            'name' => 'required|min:2',

            'table' => 'required|min:2',

            'connection' => ['required', Rule::in(array_keys(config('database.connections')))],

            'type' => 'required|in:create,edit'

        ];

    }
```

![image](https://github.com/reziamini/migrator/assets/2625865/8e5f88df-041d-4986-8fb7-8e6d4bf6efa0)

**Comment by nowodev** [comment]
This has been resolved.
#46

**Comment by reziamini** [comment]
Thanks!
