### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by relayer464** [rezaamini-ir/migrator#7]
Greetings,

This looks like a very useful package.  Unfortunately after I install it and navigate to the "migrator" URL I get the following error:

`ErrorException
Undefined offset: 1 (View: C:\laragon\www\test_project\vendor\rezaamini-ir\migrator\resources\views\livewire\migration\read.blade.php)`

Is there a compatibility issue with L8?

Thanks!

**Comment by reziamini** [comment]
I guess there is something wrong with the installation or there are some packages which are the cause of this conflict.
Please remove then reinstall the package using Composer.

**Comment by relayer464** [comment]
Thank you for the suggestion.  I tried removing and reinstalling the package but unfortunately I get the same error.

**Comment by reziamini** [comment]
Do you have a fresh installation of Laravel?
If you do, could you please tell me the exact version of your Laravel?

**Comment by relayer464** [comment]
I just tried a fresh install with the latest version of laravel:

Laravel Framework 8.76.2

Now when I navigate the /migrator URL I just get a 404 error.  I've tried clearing all caches and changing the config setting from "auth" to "web" but still get the 404.  Any suggestions?

Thanks!

P.S. Here's what my composer.json file looks like in case it is helpful:

{
    "name": "laravel/laravel",
    "type": "project",
    "description": "The Laravel Framework.",
    "keywords": [
        "framework",
        "laravel"
    ],
    "license": "MIT",
    "require": {
        "php": "^7.3|^8.0",
        "fruitcake/laravel-cors": "^2.0",
        "guzzlehttp/guzzle": "^7.0.1",
        "kyslik/column-sortable": "^6.4",
        "laravel/framework": "^8.75",
        "laravel/jetstream": "^2.3",
        "laravel/sanctum": "^2.11",
        "laravel/tinker": "^2.5",
        "livewire/livewire": "^2.0",
        "nicolaslopezj/searchable": "^1.13",
        "rezaamini-ir/migrator": "^1.3",
        "spatie/laravel-permission": "^3.17"
    },
    "require-dev": {
        "barryvdh/laravel-debugbar": "^3.6",
        "facade/ignition": "^2.5",
        "fakerphp/faker": "^1.9.1",
        "laravel/sail": "^1.0.1",
        "mockery/mockery": "^1.4.4",
        "nunomaduro/collision": "^5.10",
        "phpunit/phpunit": "^9.5.10"
    },
    "autoload": {
        "psr-4": {
            "App\\": "app/",
            "Database\\Factories\\": "database/factories/",
            "Database\\Seeders\\": "database/seeders/"
        }
    },
    "autoload-dev": {
        "psr-4": {
            "Tests\\": "tests/"
        }
    },
    "scripts": {
        "post-autoload-dump": [
            "Illuminate\\Foundation\\ComposerScripts::postAutoloadDump",
            "@php artisan package:discover --ansi"
        ],
        "post-update-cmd": [
            "@php artisan vendor:publish --tag=laravel-assets --ansi --force"
        ],
        "post-root-package-install": [
            "@php -r \"file_exists('.env') || copy('.env.example', '.env');\""
        ],
        "post-create-project-cmd": [
            "@php artisan key:generate --ansi"
        ]
    },
    "extra": {
        "laravel": {
            "dont-discover": []
        }
    },
    "config": {
        "optimize-autoloader": true,
        "preferred-install": "dist",
        "sort-packages": true
    },
    "minimum-stability": "dev",
    "prefer-stable": true
}

**Comment by reziamini** [comment]
It was fixed in `1.4.0` tag.
#9 Follow this issue and update the package, thanks!
