### ISSUE TITLE
Undefined array

### ISSUE THREAD

**Issue by shealavington** [rezaamini-ir/migrator#9]
Issue trying to install for the first time. 
Composer worked without a hitch.
Visiting the `/migrator` route seemed to fail instantly with the following.

Error:
> ErrorException
Undefined array key 1 (View: [redacted]\vendor\rezaaminiir\migrator\resources\views\livewire\migration\read.blade.php)

Code on line:
https://github.com/rezaamini-ir/migrator/blob/d30d29602cf7bb4f0e642118c800dbd33d3ba093/src/Service/StructureParser.php#L85

PHP: v8
Laravel: "laravel/framework": "^8.0",
A related issue: https://github.com/rezaamini-ir/migrator/issues/7
Line Issue Reference:

**Comment by shealavington** [comment]
When it fails, the value of "match" was `"$table->primary(['my_id', $columnNames['model_morph_key'], 'model_type'],"`. with `$table->` being removed after the substr. This fails instantly after the use of a foreign key.

This was found by changing line #21 to

```
			try {
				$type = $this->getType($match);
			} catch (\Throwable $th) {
				dd($match);
			}
```

**Comment by reziamini** [comment]
Yeah, it's related to one of your migration files.

I will try to fix it as soon as possible.

**Comment by shealavington** [comment]
Is there a particular reason it needs to parse the file? 
Does It not just tell me the migrations that have and haven't run based on their names and categorize?
Maybe I'm missing something special it's supposed to do aha?

**Comment by reziamini** [comment]
It just wants to show the structure of your migration and nothing else!
Could you please share your migration content?

**Comment by shealavington** [comment]
Understandable. 
It's even worth just adding a "catch" for "Could not generate structure at this time" to avoid a catastrophic failure.

Unfortunately due to policies, I am unable to share certain information. I'm working with a lot of migrations, while I can't provide a whole migration (also unsure of which one was failing), these are primary keys being set up, perhaps it's an issue with either string or uuid as a PK type?
```
$table->uuid('id')->primary();
$table->string('id')->primary();
```

I'd love to help out more unfortunately I don't have the time or the resource to help much more. 
I've had to drop this/your package for now but may give it another go sometime soon.
I'll try to respond with what I can but I think you're now about up to speed with the info I have.

**Comment by alaaels3id** [comment]
I got the same problem but i fix it by adding this line
if($match == 'engine = \'InnoDB\'') continue;

**Comment by reziamini** [comment]
I have made some changes and I guess these problems have been fixed in the new version.
Please update the package to `1.4.0` version with this composer command:
```bash
composer update rezaamini-ir/migrator
```
